language: node_js
node_js:
  - "node"
cache: yarn

jobs:
  include:
    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn deploy
